language: python


python:
  - "3.7"


install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install sphinx sphinx_rtd_theme pytest
  - python setup.py build build_sphinx
  - python setup.py install


script:
  - pytest --verbose tests
